language: python
before_install:
- openssl aes-256-cbc -K $encrypted_eb8cd0d5cc76_key -iv $encrypted_eb8cd0d5cc76_iv
  -in third-wharf-229116-745ee18a738c.json.enc -out third-wharf-229116-745ee18a738c.json
  -d
script:
- pytest
deploy:
  provider: gae
  keyfile: third-wharf-229116-745ee18a738c.json
  project: third-wharf-229116
